title: Arts & Science Teaching & Learning
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Access to Quercus: https://q.utoronto.ca/
